package org.example.constants;

public class Gibbet {
    public static final String GIBBET = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD_AND_RIGHT_ARM = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|              /\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD_RIGHT_ARM_AND_LEFT_ARM = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|              / \\\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD_RIGHT_ARM_LEFT_ARM_AND_STEM = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|              / \\\n")
            .append("|               |\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD_RIGHT_ARM_LEFT_ARM_STEM_AND_RIGHT_LEG = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|              / \\\n")
            .append("|               |\n")
            .append("|              /\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();

    public static final String HEAD_RIGHT_ARM_LEFT_ARM_STEM_RIGHT_LEG_AND_LEFT_LEG = new StringBuilder()
            .append("|________________\n")
            .append("|  /            |\n")
            .append("| /             |\n")
            .append("|               O\n")
            .append("|              / \\\n")
            .append("|               |\n")
            .append("|              / \\\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .append("|\n")
            .toString();
}
